version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_URL=${DB_URL}
      - TATUM_TEST_TOKEN=${TATUM_TEST_TOKEN}
      - TATUM_MAIN_TOKEN=${TATUM_MAIN_TOKEN}
    domainname: "${API_DOMAIN_NAME}"
