version: "3.8"
services:
  main:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    ports:
      - "5432:5432"
    volumes:
      - main:/var/lib/postgresql/data
volumes:
  main:
    driver: local
